[tanefont_task]

font_family = "TeX Gyre Termes"
font_weight = "400"
font_style = "regular"
map = "map01"

[kerning_table]
"A" = -1
"B" = 60
"C" = 30
"D" = 22
"E" = -6
"F" = -9
"G" = 15
"H" = 6
"I" = 5
"J" = -2
"K" = 0
"L" = -8
"M" = 5
"N" = -6

"a" = 8
"b" = 4
"c" = 25
"d" = 4
"e" = 14
"f" = -62
"i" = 10
"j" = -27
"k" = -33
"l" = 10
"s" = 59

"<<::B" = 30

"<<::i" = 5
"<<::c" = 19
"<<::f" = -22
"<<::o" = 19

"A::V" = -130
"A::v" = -70
"B::C" = 45
"B::a" = 28
"B::o" = 38
"D::e" = 19
"H::e" = 10
"M::i" = 5
"N::B" = 20
"Q::u" = 20
"V::A" = -120
"W::e" = -69
"W::N" = -15
"W::i" = -29
"W::n" = -11
"W::o" = -69

"a::c" = 25
"a::s" = 25
"c::c" = 15
"c::e" = 15
"c::i" = 20
"c::o" = 20
"d::i" = 10
"d::o" = 15
"d::t" = -10
"e::l" = 10
"g::n" = 14
"i::c" = 24
"i::d" = 9
"i::n" = 3
"i::p" = 8
"i::s" = 34
"i::t" = -5
"j::r" = -30
"l::e" = 20
"l::i" = 9
"l::o" = 20
"n::c" = 15
"n::g" = 15
"n::j" = -15
"n::t" = -5
"o::d" = 25
"o::n" = 20
"o::r" = -5
"o::s" = 42
"o::u" = 12
"p::i" = 4
"p::o" = 15
"r::d" = -5
"r::i" = 10
"r::l" = -30
"u::s" = 29
"u::r" = -12
"s::c" = 41
"s::i" = 44
"t::a" = -5
"v::a" = -16
"u::o" = 7

"0::1" = 100
"1::0" = 100
